### ISSUE TITLE
Monk trainer

### ISSUE THREAD

**Issue by Crosstnb** [milodk/AncientWoW-Bugs#48]
The monk trainer spawned at timeless isle does not work, it shows up with a "greetings COLOR" and no options to obtain duel talent spec and such.

**Comment by Ayik0** [comment]
We will not really use trainers like that, we'll have one global trainer plus we will also have commands to reset spec and such :)  

These are just temporarily :D

**Comment by LightningBlade** [comment]
Added new trainer
