### ISSUE TITLE
Blindside Proc

### ISSUE THREAD

**Issue by LightningBlade** [milodk/AncientWoW-Bugs#9]
Currently Blindside can proc of any spell or ability including auto attack, and proc chance is too high.

It will consume the proc when not using dispatch.

It's suppose to only proc on mutilate with a 30% proc chance, and only be consumed by either running out of duration or using dispatch.

**Comment by Ayik0** [comment]
Trying to fix...

**Comment by Ayik0** [comment]
Commited Fix... ToTest should work /closing
